//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrWardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeckWear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NeckWear()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int NeckWearID { get; set; }
        public string NeckWearName { get; set; }
        public string NeckWearPhotoURL { get; set; }
        public string NeckWearType { get; set; }
        public int ColorID { get; set; }
        public int OccasionID { get; set; }
        public int SeasonID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual Season Season { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
